# Неделя 1 - Воспроизводимые исследования в R

## Домашнее задание

### Пройдите вводный мини-курс на DataCamp

до `2021-09-11 09:30`

- [мини-курс Introduction to R](https://learn.datacamp.com/courses/free-introduction-to-r){target="_blank"}

- [Ссылка для регистрации в корпоративной группе DataCamp для доступа к мини-курсам](https://www.datacamp.com/groups/shared_links/968773c87ad5b5ba478379e274717c8247e48cc39a4d06704d8bdbcd2babf700){target="_blank"} - зарегистрируйте аккаунт со своей студенческой почтой на `@edu.hse.ru`


### Лабораторная в R

до `2021-09-13 12:00`

Скачайте файл лабораторной, выполните задание в файле `individual_lab_01.Rmd`. Загрузите ваш `Rmd` файл `individual_lab_01.Rmd` , убедившись, что он успешно "собирается" в `HTML` файл. Если есть ошибки при "сборке", все равно загрузите. Вы получите обратную связь и увидите, как происходит проверка домашних заданий. Оценка за эту лабораторную не идет в накопленную оценку.

- [Как загрузить и отправить выполненное задание в MS Teams](https://web.microsoftstream.com/video/33ce9c95-3c53-4f9d-aa0c-3d9d2342e055){target="_blank"}

## Лекция

**[Слайды лекции](https://eduhseru.sharepoint.com/:b:/s/2021RProgrammingforUrbanAnalytics/EYR_BgQsUKJJkSqsjojIsfoBbLxbzw0IscQPVET9AUfcjw?e=VJSwuz){target="_blank"}**


### Общая информация о курсе и система оценки

<iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/3230176c-8539-425e-b5cf-56dec5fd039e?autoplay=false&showinfo=true" allowfullscreen style="border:none;"></iframe>


- [Открыть видео в новом окне](https://web.microsoftstream.com/video/3230176c-8539-425e-b5cf-56dec5fd039e?channelId=76d212d2-0d47-461a-9295-741f7093f14e){target="_blank"}


### Воспроизводимые исследования

<iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/09e6d582-3be9-4ff7-a0d7-665a248574bb?autoplay=false&showinfo=true" allowfullscreen style="border:none;"></iframe>

- [Открыть видео в новом окне](https://web.microsoftstream.com/video/09e6d582-3be9-4ff7-a0d7-665a248574bb?channelId=76d212d2-0d47-461a-9295-741f7093f14e){target="_blank"}

## Лабораторная

### Воспроизводимые исследования в R

#### Файлы для лабораторной

Скачайте архив, распакуйте и следуйте инструкциям в видео к лабораторной, также посмотирет демонсрации первого запуска скриптов ниже.

**[Файлы для лабораторной](https://eduhseru.sharepoint.com/:u:/s/2021RProgrammingforUrbanAnalytics/Ebbh8PEUuVpKm_TlUY3yOLUB2D6Py55tWY1E5--rF0if0w?e=WH2a3L){target="_blank"}**

<iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/54a4a198-bb15-4d54-a04d-3fcbe0c3f03e?autoplay=false&showinfo=true" allowfullscreen style="border:none;"></iframe>

- [Открыть видео в новом окне](https://web.microsoftstream.com/video/54a4a198-bb15-4d54-a04d-3fcbe0c3f03e?channelId=76d212d2-0d47-461a-9295-741f7093f14e){target="_blank"}



### Демо первых запусков скриптов в лабораторной

Посмотирте видео, чтобы понять, что нужно нажать, чтобы "собрать" из Rmd файлов HTML файлы. Во время первого запуска будут достаточно долго устанавливаться пактеты для R. После первой установки "подключение" будет занимать считанные секунды.


#### в Windows

<iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/a48d7d6b-88b5-4e87-850b-cd83c2da0e7a?autoplay=false&showinfo=true" allowfullscreen style="border:none;"></iframe>

[Открыть видео в новом окне](https://web.microsoftstream.com/embed/video/a48d7d6b-88b5-4e87-850b-cd83c2da0e7a){target="_blank"}

#### в macOS

<iframe width="640" height="360" src="https://web.microsoftstream.com/embed/video/209c41bb-e90a-4781-8f76-d46a0d899298?autoplay=false&showinfo=true" allowfullscreen style="border:none;"></iframe>

[Открыть видео в новом окне](https://web.microsoftstream.com/video/209c41bb-e90a-4781-8f76-d46a0d899298?channelId=76d212d2-0d47-461a-9295-741f7093f14e){target="_blank"}


## Дополнительные ссылки из лекции и семинаров - способы использования R

### Интерактивные карты

Сайт: [https://dashboards.cbs.nl/v1/commutingNL/](https://dashboards.cbs.nl/v1/commutingNL/){target="_blank"}

Исходный код для сайта: [https://github.com/mtennekes/donutmaps](https://github.com/mtennekes/donutmaps){target="_blank"}

Данный пример использует множество пакетов, самостоятлено написанных экспериментальных пакетов, так что просто так его запустить локально не получится. Позже в курсе поговорим о том, как когда и зачем устанавливать такие пакеты с GitHub.


### Статьи в научных журналах

Статья: [https://link.springer.com/article/10.1007/s10489-021-02645-3](https://link.springer.com/article/10.1007/s10489-021-02645-3){target="_blank"}

Код для статьи: [https://github.com/fterroso/GNN-nation-wide-mob-predictor](https://github.com/fterroso/GNN-nation-wide-mob-predictor){target="_blank"}



### Книги

Книга по библиотеке ggplot2: [https://ggplot2-book.org/](https://ggplot2-book.org/){target="_blank"}

Книга Geocomputation with R: [https://geocompr.robinlovelace.net/](https://geocompr.robinlovelace.net/){target="_blank"}



### Интерактивные сайты

Галерея приложений, написанных на R + Shiny: [https://shiny.rstudio.com/gallery/](https://shiny.rstudio.com/gallery/){target="_blank"}

### Сайты-портфолио

Личный сайт автора Geocomputation with R [https://www.robinlovelace.net/](https://www.robinlovelace.net/){target="_blank"}

### Статические веб-сайты с документацией по пакетам R

Сайт о пакете `sfnetworks` [https://luukvdmeer.github.io/sfnetworks/index.html](https://luukvdmeer.github.io/sfnetworks/index.html){target="_blank"}


### Редактор Markdown

Онлайн редактор Markdown - Dillinger: [https://dillinger.io/](https://dillinger.io/){target="_blank"}


## Где писать на R онлайн

Домашние задания лучше делать на локальном компьютере, либо нужно разбираться, как загружать файлы в эти платформы. Только RStudio Cloud поддерживает Rmd формат файлов.

### Rstudio Cloud

Только RStudio Cloud поддерживает Rmd формат файлов.

[https://rstudio.cloud/projects](https://rstudio.cloud/projects){target="_blank"}

### Kaggle

У Kaggle свой формат "ноутбуков" для кода, оттуда не получится скачать Rmd файл.

[https://www.kaggle.com/code](https://www.kaggle.com/code){target="_blank"}

### Google Colab

Colab поддерижвает Jupyter ноутбуки, в которых можно писать код на R.

[https://colab.research.google.com/#create=true&language=r](https://colab.research.google.com/#create=true&language=r){target="_blank"}

