---
title: 'Домашняя страница курса "Программирование для анализа городских данных 2021"'
author: '[Егор Котов, старший преподаватель, научный сотрудник НИУ ВШЭ](https://www.hse.ru/staff/ekotov){target="_blank"}; <br>[Юрий Кульчицкий, преподаватель, аналитик НИУ ВШЭ](https://www.hse.ru/staff/kulchitsky){target="_blank"}'
documentclass: book
knit: bookdown::render_book
site: bookdown::bookdown_site
  # output:
  # bookdown::gitbook:
  #   includes:
  #     in_header: ga.html
---

# Главная

- [Страница курса на сайте ВШЭ](https://www.hse.ru/edu/courses/450799729){target="_blank"}

- [Анонимная форма для вопросов по курсу и выражения мнения](https://forms.office.com/r/EWcUi13QCN){target="_blank"}

- [Как загрузить и отправить выполненное задание в MS Teams](https://web.microsoftstream.com/video/33ce9c95-3c53-4f9d-aa0c-3d9d2342e055){target="_blank"}

- [Канал с видеозаписями курса](https://web.microsoftstream.com/channel/76d212d2-0d47-461a-9295-741f7093f14e){target="_blank"}

- 
[Ссылка для регистрации в корпоративной группе DataCamp для доступа к мини-курсам](https://www.datacamp.com/groups/shared_links/968773c87ad5b5ba478379e274717c8247e48cc39a4d06704d8bdbcd2babf700){target="_blank"} - зарегистрируйте аккаунт со своей студенческой почтой на `@edu.hse.ru`

## Установка R

- [Видео - как установить в macOS](https://web.microsoftstream.com/video/e9142ea1-01d6-452f-90b8-1728977fa3cf?list=studio){target="_blank"}

- [Видео - как установить в Windows](https://web.microsoftstream.com/video/2ff6ae6b-da85-44b1-b1d8-644032670a52?list=studio){target="_blank"}

## Где скачать R + RStudio

- [R и Rtools (второе только для Windows)](https://cran.r-project.org/){target="_blank"}

- [RStudio](https://www.rstudio.com/products/rstudio/download/){target="_blank"}

## Настройка RStudio

- [Оптимальная настройка `RStudio` для работы во время курса](https://web.microsoftstream.com/video/4c8b1b32-4378-402b-8c2c-7c44c55a087a?list=studio){target="_blank"}

## Лабораторные на оценку

- [Лабораторная 1](/%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-2---%D0%B1%D0%B0%D0%B7%D0%BE%D0%B2%D1%8B%D0%B5-%D1%82%D0%B8%D0%BF%D1%8B-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D0%B8-%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D1%8B.html#%D0%BB%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F-01---%D0%BD%D0%B0-%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D1%83) (0.05 в итоговой, макс. 10 баллов, сдача до `2021-09-27 12:00`)


## ШПАРГАЛКИ

- Манипуляция таблицами - [`dplyr`](https://github.com/rstudio/cheatsheets/blob/master/data-transformation.pdf){target="_blank"}

- Манипуляция датами - [`lubridate`](https://rawgit.com/rstudio/cheatsheets/master/lubridate.pdf){target="_blank"}

- [Работа с Markdown файлами](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown.pdf){target="_blank"}

- [Работа с RStudio](https://github.com/rstudio/cheatsheets/raw/master/rstudio-ide.pdf){target="_blank"}

- [Больше шпаргалок по всем темам...](https://www.rstudio.com/resources/cheatsheets/){target="_blank"}

<!-- If you need PDF output, uncomment bookdown::pdf_book above in YAML. You will need a LaTeX installation, e.g., https://yihui.name/tinytex/ -->

## Типовые проблемы и решения

### У меня русские пути к библиотеке пакетов и из-за этого не работает нормально установка пакетов

Попробуйте создать новую папку, например, `c:/rpackages/` и добавьте путь к ней, следуя инструкциям по ссылке [https://www.accelebrate.com/library/how-to-articles/r-rstudio-library](https://www.accelebrate.com/library/how-to-articles/r-rstudio-library){target="_blank"} - там см. последний раздел **Making Your Library Changes Permanent**


